import { Event, Season, DriverStanding, ConstructorStanding } from "@/types";

export const mockSeasons: Season[] = [
    { year: 2024, totalRounds: 24 },
    { year: 2023, totalRounds: 22 },
    { year: 2022, totalRounds: 22 },
];

export const mockEvents: Event[] = [
    {
        id: "2024_1",
        seasonYear: 2024,
        roundNumber: 1,
        eventName: "Bahrain Grand Prix",
        country: "Bahrain",
        circuitKey: "bahrain",
        circuitName: "Bahrain International Circuit",
        eventDate: "2024-03-02",
        eventFormat: "conventional",
        sessions: [
            { sessionType: "FP1", date: "2024-03-01T11:30:00Z", status: "completed" },
            { sessionType: "FP2", date: "2024-03-01T15:00:00Z", status: "completed" },
            { sessionType: "FP3", date: "2024-03-02T12:30:00Z", status: "completed" },
            { sessionType: "Q", date: "2024-03-02T16:00:00Z", status: "completed" },
            { sessionType: "R", date: "2024-03-03T15:00:00Z", status: "completed" },
        ],
    },
    {
        id: "2024_2",
        seasonYear: 2024,
        roundNumber: 2,
        eventName: "Saudi Arabian Grand Prix",
        country: "Saudi Arabia",
        circuitKey: "jeddah",
        circuitName: "Jeddah Corniche Circuit",
        eventDate: "2024-03-09",
        eventFormat: "conventional",
        sessions: [
            { sessionType: "FP1", date: "2024-03-08T13:30:00Z", status: "completed" },
            { sessionType: "FP2", date: "2024-03-08T17:00:00Z", status: "completed" },
            { sessionType: "FP3", date: "2024-03-09T13:30:00Z", status: "completed" },
            { sessionType: "Q", date: "2024-03-09T17:00:00Z", status: "completed" },
            { sessionType: "R", date: "2024-03-10T17:00:00Z", status: "completed" },
        ],
    },
    {
        id: "2024_3",
        seasonYear: 2024,
        roundNumber: 3,
        eventName: "Australian Grand Prix",
        country: "Australia",
        circuitKey: "albert_park",
        circuitName: "Albert Park Circuit",
        eventDate: "2024-03-24",
        eventFormat: "conventional",
        sessions: [
            { sessionType: "FP1", date: "2024-03-22T01:30:00Z", status: "completed" },
            { sessionType: "FP2", date: "2024-03-22T05:00:00Z", status: "completed" },
            { sessionType: "FP3", date: "2024-03-23T01:30:00Z", status: "completed" },
            { sessionType: "Q", date: "2024-03-23T05:00:00Z", status: "completed" },
            { sessionType: "R", date: "2024-03-24T04:00:00Z", status: "completed" },
        ],
    },
    {
        id: "2024_4",
        seasonYear: 2024,
        roundNumber: 4,
        eventName: "Japanese Grand Prix",
        country: "Japan",
        circuitKey: "suzuka",
        circuitName: "Suzuka International Racing Course",
        eventDate: "2024-04-07",
        eventFormat: "conventional",
        sessions: [
            { sessionType: "FP1", date: "2024-04-05T02:30:00Z", status: "completed" },
            { sessionType: "FP2", date: "2024-04-05T06:00:00Z", status: "completed" },
            { sessionType: "FP3", date: "2024-04-06T02:30:00Z", status: "completed" },
            { sessionType: "Q", date: "2024-04-06T06:00:00Z", status: "completed" },
            { sessionType: "R", date: "2024-04-07T05:00:00Z", status: "completed" },
        ],
    },
    {
        id: "2024_5",
        seasonYear: 2024,
        roundNumber: 5,
        eventName: "Chinese Grand Prix",
        country: "China",
        circuitKey: "shanghai",
        circuitName: "Shanghai International Circuit",
        eventDate: "2024-04-21",
        eventFormat: "sprint",
        sessions: [
            { sessionType: "FP1", date: "2024-04-19T03:30:00Z", status: "completed" },
            { sessionType: "SQ", date: "2024-04-19T07:30:00Z", status: "completed" },
            { sessionType: "S", date: "2024-04-20T03:00:00Z", status: "completed" },
            { sessionType: "Q", date: "2024-04-20T07:00:00Z", status: "completed" },
            { sessionType: "R", date: "2024-04-21T07:00:00Z", status: "completed" },
        ],
    },
    {
        id: "2024_6",
        seasonYear: 2024,
        roundNumber: 6,
        eventName: "Miami Grand Prix",
        country: "Miami",
        circuitKey: "miami",
        circuitName: "Miami International Autodrome",
        eventDate: "2024-05-05",
        eventFormat: "sprint",
        sessions: [
            { sessionType: "FP1", date: "2024-05-03T16:30:00Z", status: "completed" },
            { sessionType: "SQ", date: "2024-05-03T20:30:00Z", status: "completed" },
            { sessionType: "S", date: "2024-05-04T16:00:00Z", status: "completed" },
            { sessionType: "Q", date: "2024-05-04T20:00:00Z", status: "completed" },
            { sessionType: "R", date: "2024-05-05T20:00:00Z", status: "completed" },
        ],
    },
    {
        id: "2024_7",
        seasonYear: 2024,
        roundNumber: 7,
        eventName: "Emilia Romagna Grand Prix",
        country: "Emilia",
        circuitKey: "imola",
        circuitName: "Autodromo Enzo e Dino Ferrari",
        eventDate: "2024-05-19",
        eventFormat: "conventional",
        sessions: [
            { sessionType: "FP1", date: "2024-05-17T11:30:00Z", status: "completed" },
            { sessionType: "FP2", date: "2024-05-17T15:00:00Z", status: "completed" },
            { sessionType: "FP3", date: "2024-05-18T10:30:00Z", status: "completed" },
            { sessionType: "Q", date: "2024-05-18T14:00:00Z", status: "completed" },
            { sessionType: "R", date: "2024-05-19T13:00:00Z", status: "completed" },
        ],
    },
    {
        id: "2024_8",
        seasonYear: 2024,
        roundNumber: 8,
        eventName: "Monaco Grand Prix",
        country: "Monaco",
        circuitKey: "monaco",
        circuitName: "Circuit de Monaco",
        eventDate: "2024-05-26",
        eventFormat: "conventional",
        sessions: [
            { sessionType: "FP1", date: "2024-05-24T11:30:00Z", status: "completed" },
            { sessionType: "FP2", date: "2024-05-24T15:00:00Z", status: "completed" },
            { sessionType: "FP3", date: "2024-05-25T10:30:00Z", status: "completed" },
            { sessionType: "Q", date: "2024-05-25T14:00:00Z", status: "completed" },
            { sessionType: "R", date: "2024-05-26T13:00:00Z", status: "completed" },
        ],
    },
    {
        id: "2024_9",
        seasonYear: 2024,
        roundNumber: 9,
        eventName: "Canadian Grand Prix",
        country: "Canada",
        circuitKey: "montreal",
        circuitName: "Circuit Gilles-Villeneuve",
        eventDate: "2024-06-09",
        eventFormat: "conventional",
        sessions: [
            { sessionType: "R", date: "2024-06-09T18:00:00Z", status: "completed" },
        ],
    },
    {
        id: "2024_10",
        seasonYear: 2024,
        roundNumber: 10,
        eventName: "Spanish Grand Prix",
        country: "Spain",
        circuitKey: "barcelona",
        circuitName: "Circuit de Barcelona-Catalunya",
        eventDate: "2024-06-23",
        eventFormat: "conventional",
        sessions: [
            { sessionType: "R", date: "2024-06-23T13:00:00Z", status: "completed" },
        ],
    },
    {
        id: "2024_11",
        seasonYear: 2024,
        roundNumber: 11,
        eventName: "Austrian Grand Prix",
        country: "Austria",
        circuitKey: "red_bull_ring",
        circuitName: "Red Bull Ring",
        eventDate: "2024-06-30",
        eventFormat: "sprint",
        sessions: [
            { sessionType: "R", date: "2024-06-30T13:00:00Z", status: "completed" },
        ],
    },
    {
        id: "2024_12",
        seasonYear: 2024,
        roundNumber: 12,
        eventName: "British Grand Prix",
        country: "Great Britain",
        circuitKey: "silverstone",
        circuitName: "Silverstone Circuit",
        eventDate: "2024-07-07",
        eventFormat: "conventional",
        sessions: [
            { sessionType: "R", date: "2024-07-07T14:00:00Z", status: "completed" },
        ],
    },
];

export const mockDriverStandings: DriverStanding[] = [
    { position: 1, driver: "Max Verstappen", driverAbbr: "VER", team: "Red Bull Racing", teamColor: "#3671C6", points: 575, wins: 19, nationality: "Dutch" },
    { position: 2, driver: "Lando Norris", driverAbbr: "NOR", team: "McLaren", teamColor: "#FF8000", points: 374, wins: 4, nationality: "British" },
    { position: 3, driver: "Charles Leclerc", driverAbbr: "LEC", team: "Ferrari", teamColor: "#E8002D", points: 356, wins: 3, nationality: "Monegasque" },
    { position: 4, driver: "Oscar Piastri", driverAbbr: "PIA", team: "McLaren", teamColor: "#FF8000", points: 292, wins: 2, nationality: "Australian" },
    { position: 5, driver: "Carlos Sainz", driverAbbr: "SAI", team: "Ferrari", teamColor: "#E8002D", points: 290, wins: 2, nationality: "Spanish" },
    { position: 6, driver: "Lewis Hamilton", driverAbbr: "HAM", team: "Mercedes", teamColor: "#27F4D2", points: 211, wins: 2, nationality: "British" },
    { position: 7, driver: "George Russell", driverAbbr: "RUS", team: "Mercedes", teamColor: "#27F4D2", points: 207, wins: 1, nationality: "British" },
    { position: 8, driver: "Sergio Pérez", driverAbbr: "PER", team: "Red Bull Racing", teamColor: "#3671C6", points: 152, wins: 0, nationality: "Mexican" },
    { position: 9, driver: "Fernando Alonso", driverAbbr: "ALO", team: "Aston Martin", teamColor: "#229971", points: 70, wins: 0, nationality: "Spanish" },
    { position: 10, driver: "Pierre Gasly", driverAbbr: "GAS", team: "Alpine", teamColor: "#FF87BC", points: 42, wins: 0, nationality: "French" },
];

export const mockConstructorStandings: ConstructorStanding[] = [
    { position: 1, constructor: "McLaren", teamColor: "#FF8000", points: 666, wins: 6 },
    { position: 2, constructor: "Ferrari", teamColor: "#E8002D", points: 652, wins: 5 },
    { position: 3, constructor: "Red Bull Racing", teamColor: "#3671C6", points: 589, wins: 9 },
    { position: 4, constructor: "Mercedes", teamColor: "#27F4D2", points: 425, wins: 3 },
    { position: 5, constructor: "Aston Martin", teamColor: "#229971", points: 94, wins: 0 },
];
